### Task 1


In [24]:
def expression1(x):
  return 5*x**4 + 4*x**3 + 3*x**2 +2

def expression2(x):
    return ((3*x**2 +7*x)/4) -((2*x)/5)

for i in range(1,6):
    print(f"x={i}: Expression 1 = {expression1(i)}, Expression 2 = {expression2(i)}")


x=1: Expression 1 = 14, Expression 2 = 2.1
x=2: Expression 1 = 126, Expression 2 = 5.7
x=3: Expression 1 = 542, Expression 2 = 10.8
x=4: Expression 1 = 1586, Expression 2 = 17.4
x=5: Expression 1 = 3702, Expression 2 = 25.5


### Task 2

In [25]:
variable1 = int(input("Enter first integer"))
variable2 = int(input("Enter second integer"))

if(variable1 % variable2 == 0):
 print(f'{variable1} is multiple of {variable2}')
else: 
 print(f'{variable1} is not multiple of {variable2}')


9 is multiple of 3


### Task 3

In [26]:
members = {229252:"tazmeen" ,229253 :"tooba",229256:"anya"}
reg_sum = 0
for k,v in members.items():
    reg_sum += k
    print(f'{k} : {v}')
print(f'sum is {reg_sum}')


# OR

members ={"reg_no":[229252,229253,229256],"name":["tazmeen","tooba","anya"]}
reg_sum = 0
for i in range(len(members["reg_no"])):
    reg_sum += members["reg_no"][i]
    print(f'{members["reg_no"][i]} : {members["name"][i]}')
print(f'sum is {reg_sum}')


229252 : tazmeen
229253 : tooba
229256 : anya
sum is 687761
229252 : tazmeen
229253 : tooba
229256 : anya
sum is 687761


### Task 4

In [27]:
def check(a,b):
    if(a>0 and b>0):
     print("Both numbers are positive")
    elif(a==0 and b==0):
     print("Both numbers  are zero")
    elif (a == b):
      print("Both numbers are equal")
    elif (a < 0 and b <0):
      print("Both numbers are negative")
    elif((a>0 and b <0) or (b >0 and a <0)):
      print("One number is positive and one number is negative") 
    elif(a == 0 or b== 0):
       print("At least one number is zero")

a = int(input("Enter first number"))
b = int(input("Enter second number"))

print("first number is",a)
print("second number is",b)
print("Results:")
check(a,b)

first number is 5
second number is -5
Results:
One number is positive and one number is negative


### Task 5

In [28]:
number = int(input("Enter a number to calculate factorial"))
n = number
factorial = 1
while(number > 0):
    factorial = factorial * number
    number = number - 1

print(f'Factorial  of {n} is {factorial}')



Factorial  of 5 is 120


### Task 6

In [29]:
number1 = int(input("Enter first number"))
number2 = int(input("Enter second number"))
sign = 1

def product(a,b):
    if(b==0 or a==0):
        return 0
    elif(b<0 and a<0):
        b = -b
        a = -a
    elif(b<0 or a<0):
        if(b<0):
            b = -b
        else:
            a = -a
        sign = -1
    else:
        sign = 1
    sum = 0
    for i in range(b):
        sum+=a
    return sign*sum

print(f'Product of {number1} and {number2} is {product(number1,number2)}')

Product of 4 and -3 is -12


### Task 7

In [30]:
mem1 = input("Enter first member name")
mem2 = input("Enter second member name")    
mem3 = input("Enter third member name")

def members(mem1,mem2,mem3):
   final = mem1+ mem2 + mem3
   for i in final:
      print(f"{i}")
   print(f'Total characters are {len(final)}')

members(mem1,mem2,mem3)

t
a
z
m
e
e
n
t
o
o
b
a
a
n
y
a
Total characters are 16


### Task 8

In [31]:
def multiply(n):
    for i in range(1,11):
       print(f'{n*i}',end=" ,")

for i in range(1,11):
    multiply(i)
    print("\n")


1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,

2 ,4 ,6 ,8 ,10 ,12 ,14 ,16 ,18 ,20 ,

3 ,6 ,9 ,12 ,15 ,18 ,21 ,24 ,27 ,30 ,

4 ,8 ,12 ,16 ,20 ,24 ,28 ,32 ,36 ,40 ,

5 ,10 ,15 ,20 ,25 ,30 ,35 ,40 ,45 ,50 ,

6 ,12 ,18 ,24 ,30 ,36 ,42 ,48 ,54 ,60 ,

7 ,14 ,21 ,28 ,35 ,42 ,49 ,56 ,63 ,70 ,

8 ,16 ,24 ,32 ,40 ,48 ,56 ,64 ,72 ,80 ,

9 ,18 ,27 ,36 ,45 ,54 ,63 ,72 ,81 ,90 ,

10 ,20 ,30 ,40 ,50 ,60 ,70 ,80 ,90 ,100 ,



### Task 9

In [ ]:
name = "tazmeen"

namel = list(name)

print(namel)

for i in range(len(namel)):
    print(namel[i])

['t', 'a', 'z', 'm', 'e', 'e', 'n']
t
a
z
m
e
e
n


### Task 10

In [36]:
new = ""
newlist = []
while(new.lower() != "done"):
  new = input("Enter a number to add to the list or type done to stop: ")
  if(new.lower() != "done"):
        intnew = int(new)
        if(newlist == []):
            newlist.append(intnew)
        else:
            for i in range(len(newlist)):
                if(intnew <= newlist[i]):
                    newlist.insert(i,intnew)
                    break
                elif(i == len(newlist)-1):
                    newlist.append(intnew)
                    break
  print("Final sorted list is ",newlist)


Final sorted list is  [3]
Final sorted list is  [3, 5]
Final sorted list is  [2, 3, 5]
Final sorted list is  [1, 2, 3, 5]
Final sorted list is  [0, 1, 2, 3, 5]
Final sorted list is  [-1, 0, 1, 2, 3, 5]
Final sorted list is  [-3, -1, 0, 1, 2, 3, 5]
Final sorted list is  [-3, -2, -1, 0, 1, 2, 3, 5]
Final sorted list is  [-3, -2, -1, 0, 1, 2, 3, 5, 6]
Final sorted list is  [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6]
Final sorted list is  [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6]


### Task 11

In [37]:
l = []
for i in range(1,21):
    l.append(i)
print(l)

list1 = l[4:]
print(list1)

list2 = l[0:12]
print(list2)

list3 = l[6:16]
print(list3)

list4 = l[3:5]
print(list4)

list5 = l[10:14]
print(list5)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
[4, 5]
[11, 12, 13, 14]


### Task 12

In [39]:
value = 0
keys = {}
while(value != 5):
    key = input(f'Enter the value of key {value}: ')
    value += 1
    keys[key] = None

for k,v in keys.items():
   v = input(f'Enter the value for key {k}: ')
   keys[k] = v
print(keys)

    

{'mango': '3', 'apple': '2', 'dragonfruit': '5', 'cherry': '2', 'pear': '1'}


### Task 13

In [40]:
import random
import math

def sine(start,end):
    rand_no =random.randint(start,end)
    sine_value = math.sin(rand_no)
    print(f'sine value of {rand_no} is {sine_value}')


for i in range(1,6):
    sine(1,10)

sine value of 5 is -0.9589242746631385
sine value of 3 is 0.1411200080598672
sine value of 8 is 0.9893582466233818
sine value of 1 is 0.8414709848078965
sine value of 3 is 0.1411200080598672


### Task 14

In [41]:
import numpy as np


array1 = np.array(np.random.randint(1, 50, size=(7, 7)))
print(array1)
print("Shape of the array:", array1.shape)
print(array1[2, 2]) 
print(array1[1:3, :]) 
print(array1[2:5, 2:5])  
print("Sum :", np.sum(array1))
print("Sum along axis 0:", np.sum(array1, axis=0))
print("Sum along axis 1:", np.sum(array1, axis=1))
print("Mean of all elements:", np.mean(array1))
print("Standard deviation:", np.std(array1))

[[24 26 17 12 33  6  8]
 [ 9 19 47 34 36 45 49]
 [12 43 12  4 36 28 27]
 [22 15 42 40 41 26 22]
 [45 14 27 16 18  7 40]
 [10 33 44 30 13 21 26]
 [12  6 41 48 45 29  1]]
Shape of the array: (7, 7)
12
[[ 9 19 47 34 36 45 49]
 [12 43 12  4 36 28 27]]
[[12  4 36]
 [42 40 41]
 [27 16 18]]
Sum : 1261
Sum along axis 0: [134 156 230 184 222 162 173]
Sum along axis 1: [126 239 162 208 167 177 182]
Mean of all elements: 25.73469387755102
Standard deviation: 13.813296626142481
